PHP: true

exclude_paths:
 - "**/vendor/"
 - "build/"
 - "doc/"
 - "tests/"

engines:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "PSR1,PSR2"
  phpmd:
    enabled: true
    config:
      file_extensions: "php"

ratings:
  paths:
  - "**.php"
