PHP: true

exclude_paths:
 - "**/vendor/"
 - "build/"
 - "doc/"
 - "tests/"

engines:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "PSR1,PSR2"
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "cleancode,controversial,design,codesize,unusedcode,ic_ruleset.xml"
  duplication:
    enabled: true
    config:
      languages:
        php:
          mass_threshold: 25
ratings:
  paths:
  - "**.php"
