# specify language to use
language: php

# select build environment
# Ubuntu Trusty
# container based
# 4GB max, 2 cores
dist: trusty
sudo: false

# which directories should be cached
cache:
    directories:
        - $HOME/.composer/cache/files
        - vendor

php:
    - 7.0
    - 7.1
    - 7.2
    - nightly

env:
matrix:
    # mark as finished before allow_failures are run
    fast_finish: trues
    # nightly can fail
    allow_failures:
        - php: nightly

# test only master (+ pull requests)
branches:
  only:
    - master
    - 1.x
# set CodeClimate test reporter
before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build

# make sure to update composer to latest available version
before_install:
    - phpenv config-add travis.php.ini

# install dependencies
install:
    - composer install

# execute phpunit as the script command
script:
  - ./vendor/bin/phpunit -d memory_limit=-1 --colors -c phpunit.xml.dist --coverage-clover=coverage.xml

# disable mail notifications
notification:
  email: false

# reduce depth (history) of git checkout
git:
  depth: 30

# enable scrutinizer
# after_script:
#  - wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover
# process coverage to CodeClimate
after_script:
    - ./cc-test-reporter format-coverage --coverage-input-type clover < coverage.xml
    - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

# send coverage to codecov.io
after_success:
    - bash <(curl -s https://codecov.io/bash)
