ez_systems_extending_platform_ui_conference_homepage:
    path:     /
    defaults: { _controller: EzSystemsExtendingPlatformUIConferenceBundle:Default:index }

admin_contenttypeView:
    path: /contenttype/view/{contentTypeId}/{languageCode}
    defaults:
        _controller: netgen.platformui.controller.content_type:viewContentTypeAction
        languageCode: ~

admin_contenttypeUpdate:
    path: /contenttype/update/{contentTypeId}/{languageCode}
    defaults:
        _controller: netgen.platformui.controller.content_type:updateContentTypeAction
        languageCode: ~
