services:
    netgen_information_collection.action.registry:
        class: Netgen\Bundle\InformationCollectionBundle\Action\ActionRegistry
        public: false
        arguments:
            - "$actions;netgen_information_collection$"
            - "@logger"
        calls:
            - [setDebug, ['%kernel.debug%']]

    netgen_information_collection.action.db:
        class: Netgen\Bundle\InformationCollectionBundle\Action\DatabaseAction
        public: false
        arguments:
            - '@netgen_information_collection.factory.field_data'
            - '@netgen_information_collection.repository_aggregate'
            - '@ezpublish.api.repository'
        tags:
            - { name: netgen_information_collection.action, alias: database, priority: 300 }

    netgen_information_collection.action.email:
        class: Netgen\Bundle\InformationCollectionBundle\Action\EmailAction
        public: false
        arguments:
            - '@netgen_information_collection.factory.email_data'
            - '@netgen_information_collection.mailer'
        tags:
            - { name: netgen_information_collection.action, alias: email }
