imports:
    - { resource: actions.yml }
    - { resource: storage.yml }
    - { resource: factories.yml }

parameters:
    # Controllers
    netgen_information_collection.controller.class: Netgen\Bundle\InformationCollectionBundle\Controller\InformationCollectionController
    netgen_information_collection_legacy.controller.class: Netgen\Bundle\InformationCollectionBundle\Controller\InformationCollectionLegacyController
    netgen_information_collection.form.builder.class: Netgen\Bundle\InformationCollectionBundle\Form\Builder\FormBuilder
    # END of Controllers

    # Listeners
    netgen_information_collection.listener.class: Netgen\Bundle\InformationCollectionBundle\Listener\InformationCollectedListener
    # END of Listeners

    # Handler registry
    netgen_information_collection.field_handler.registry.class: Netgen\Bundle\InformationCollectionBundle\FieldHandler\FieldHandlerRegistry
    # END of Handler registry

    # Mailer
    netgen_information_collection.mailer.class: Netgen\Bundle\InformationCollectionBundle\Mailer\Mailer
    # END of Mailer
services:
    netgen_information_collection.controller:
        class: '%netgen_information_collection.controller.class%'
        calls:
            - [setContainer, ['@service_container']]

    information_collection:
        alias: 'netgen_information_collection.controller'

    netgen_information_collection_legacy.controller:
        class: '%netgen_information_collection_legacy.controller.class%'
        calls:
            - [setContainer, ['@service_container']]

    information_collection_legacy:
        alias: 'netgen_information_collection_legacy.controller'

    netgen_information_collection.form.builder:
        class: '%netgen_information_collection.form.builder.class%'
        arguments:
            - '@form.factory'
            - '@ezpublish.api.service.content_type'
            - '@router'
            - '%netgen.default.information_collection.form.use_csrf%'

    netgen_information_collection.listener:
        class: '%netgen_information_collection.listener.class%'
        arguments:
            - '@netgen_information_collection.action.registry'
        tags:
            - { name: kernel.event_subscriber }

    netgen_information_collection.field_handler.registry:
        class: '%netgen_information_collection.field_handler.registry.class%'

    netgen_information_collection.mailer:
        class: '%netgen_information_collection.mailer.class%'
        arguments:
            - '@mailer'

    netgen_information_collection.controller.content_type:
        class: Netgen\Bundle\InformationCollectionBundle\Controller\ContentTypeController
        parent: ezsystems.platformui.controller.base
        arguments:
            - "@ezpublish.api.service.content_type"
            - "@ezpublish.api.service.search"
            - "@ezpublish.api.service.user"
            - "@ezrepoforms.action_dispatcher.content_type.group"
            - "@ezrepoforms.action_dispatcher.content_type"
            - "@ezrepoforms.field_type_form_mapper.registry"
        calls:
            - [setPrioritizedLanguages, ["$languages$"]]

    ezrepoforms.content_type.update.form_type:
        class: Netgen\Bundle\InformationCollectionBundle\Form\Type\ContentType\ContentTypeUpdateType
        arguments: ["@ezpublish.field_type_collection.factory", "@translator"]
        tags:
            - {name: form.type, alias: ezrepoforms_contenttype_update}

    ezrepoforms.field_definition.form_type:
        class: Netgen\Bundle\InformationCollectionBundle\Form\Type\FieldDefinition\FieldDefinitionType
        arguments: ["@ezrepoforms.field_type_form_mapper.dispatcher", "@ezpublish.api.service.field_type"]
        calls:
            - [setGroupsList, ["@ezpublish.fields_groups.list"]]
        tags:
            - { name: form.type, alias: ezrepoforms_fielddefinition_update }
