imports:
    - { resource: actions.yml }
    - { resource: storage.yml }
    - { resource: factories.yml }
    - { resource: form.yml }

services:
    netgen_information_collection.controller:
        class: Netgen\Bundle\InformationCollectionBundle\Controller\InformationCollectionController
        calls:
            - [setContainer, ['@service_container']]

    information_collection:
        alias: 'netgen_information_collection.controller'

    netgen_information_collection.form.builder:
        class: Netgen\Bundle\InformationCollectionBundle\Form\Builder\FormBuilder
        arguments:
            - '@form.factory'
            - '@ezpublish.api.service.content_type'
            - '@router'
            - '%netgen.default.information_collection.form.use_csrf%'

    netgen_information_collection.listener:
        class: Netgen\Bundle\InformationCollectionBundle\Listener\InformationCollectedListener
        arguments:
            - '@netgen_information_collection.action.registry'
        tags:
            - { name: kernel.event_subscriber }

    netgen_information_collection.field_handler.registry:
        class: Netgen\Bundle\InformationCollectionBundle\FieldHandler\FieldHandlerRegistry

    netgen_information_collection.mailer:
        class: Netgen\Bundle\InformationCollectionBundle\Mailer\Mailer
        arguments:
            - '@mailer'

    netgen_information_collection.controller.content_type:
        class: Netgen\Bundle\InformationCollectionBundle\Controller\ContentTypeController
        parent: ezsystems.platformui.controller.content_type

    netgen.field_definition.form_type_extension:
        class: Netgen\Bundle\InformationCollectionBundle\Form\Extension\FieldDefinitionTypeExtension
        tags:
            - { name: form.type_extension, extended_type: EzSystems\RepositoryForms\Form\Type\FieldDefinition\FieldDefinitionType }

    netgen.content_type.update.form_type_extension:
        class: Netgen\Bundle\InformationCollectionBundle\Form\Extension\ContentTypeUpdateTypeExtension
        tags:
            - { name: form.type_extension, extended_type: EzSystems\RepositoryForms\Form\Type\ContentType\ContentTypeUpdateType }
