services:
    netgen_information_collection.repository_aggregate:
        class: Netgen\Bundle\InformationCollectionBundle\Repository\RepositoryAggregate
        public: false
        arguments:
            - "@netgen_information_collection.repository.ez_info_collection"
            - "@netgen_information_collection.repository.ez_info_collection_attribute"

    netgen_information_collection.repository.ez_info_collection:
        class: Netgen\Bundle\InformationCollectionBundle\Repository\EzInfoCollectionRepository
        public: false
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Netgen\Bundle\InformationCollectionBundle\Entity\EzInfoCollection

    netgen_information_collection.repository.ez_info_collection_attribute:
        class: Netgen\Bundle\InformationCollectionBundle\Repository\EzInfoCollectionAttributeRepository
        public: false
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Netgen\Bundle\InformationCollectionBundle\Entity\EzInfoCollectionAttribute
